#ifndef TOKEN_H
#define TOKEN_H

#include <stdbool.h>
#include <stdio.h>

typedef enum TokenType
{
    TOKEN_IF,
    TOKEN_UNLESS,
    TOKEN_ELSE,
    TOKEN_IN,
    TOKEN_IS,
    TOKEN_HAS,
    TOKEN_SIZEOF,
    TOKEN_TYPEOF,
    TOKEN_FOR,
    TOKEN_WHILE,
    TOKEN_MATCH,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_WHERE,
    TOKEN_RETURN,
    TOKEN_YIELD,
    TOKEN_AS,
    TOKEN_VAR,
    TOKEN_LET,
    TOKEN_STATIC,
    TOKEN_CONST,
    TOKEN_USE,
    TOKEN_END,
    TOKEN_CLASS,
    TOKEN_STRUCT,
    TOKEN_PROTOCOL,
    TOKEN_ENUM,
    TOKEN_GET,
    TOKEN_SET,
    TOKEN_FUNC,
    TOKEN_TYPE,
    TOKEN_INTERNAL,
    TOKEN_PRIVATE,
    TOKEN_PUBLIC,
    TOKEN_SELF,
    TOKEN_ASYNC,
    TOKEN_AWAIT,
    TOKEN_DEFER,
    TOKEN_EXTERN,
    TOKEN_TRY,
    TOKEN_CATCH,
    TOKEN_FINALLY,
    TOKEN_THROW,
    TOKEN_NONE,
    TOKEN_INT,
    TOKEN_UINT,
    TOKEN_INT8,
    TOKEN_INT16,
    TOKEN_INT32,
    TOKEN_INT64,
    TOKEN_UINT8,
    TOKEN_UINT16,
    TOKEN_UINT32,
    TOKEN_UINT64,
    TOKEN_FLOAT,
    TOKEN_DOUBLE,
    TOKEN_CHAR,
    TOKEN_STRING,
    TOKEN_BOOL,
    TOKEN_TRUE,
    TOKEN_FALSE,
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_STAR,
    TOKEN_SLASH,
    TOKEN_FLOOR,
    TOKEN_PERCENT,
    TOKEN_POWER,
    TOKEN_COALESCE,
    TOKEN_EQUAL,
    TOKEN_PLUS_EQUAL,
    TOKEN_MINUS_EQUAL,
    TOKEN_STAR_EQUAL,
    TOKEN_SLASH_EQUAL,
    TOKEN_FLOOR_EQUAL,
    TOKEN_PERCENT_EQUAL,
    TOKEN_POWER_EQUAL,
    TOKEN_COALESCE_EQUAL,
    TOKEN_EQUAL_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_EQUAL_EQUAL_EQUAL,
    TOKEN_NOT_EQUAL_EQUAL,
    TOKEN_EQUAL_TILDE,
    TOKEN_NOT_TILDE,
    TOKEN_GREATER,
    TOKEN_GREATER_EQUAL,
    TOKEN_LESS,
    TOKEN_LESS_EQUAL,
    TOKEN_SPACESHIP,
    TOKEN_BOOLEAN_AND,
    TOKEN_BOOLEAN_OR,
    TOKEN_EXCLAMATION,
    TOKEN_AMPERSAND,
    TOKEN_PIPE,
    TOKEN_CIRCUMFLEX,
    TOKEN_LSHIFT,
    TOKEN_RSHIFT,
    TOKEN_TILDE,
    TOKEN_QUESTION,
    TOKEN_TERNARY,
    TOKEN_COLON,
    TOKEN_AND_EQUAL,
    TOKEN_OR_EQUAL,
    TOKEN_CIRCUMFLEX_EQUAL,
    TOKEN_LSHIFT_EQUAL,
    TOKEN_RSHIFT_EQUAL,
    TOKEN_ARROW,
    TOKEN_SAFE_ACCESS,
    TOKEN_PIPE_FORWARD,
    TOKEN_PIPE_BACKWARD,
    TOKEN_DOLLAR,
    TOKEN_RANGE,
    TOKEN_RANGE_FROM_END,
    TOKEN_SPREAD,
    TOKEN_AT,
    TOKEN_DOT,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LSQUARE,
    TOKEN_RSQUARE,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_SEMICOLON,
    TOKEN_COMMA,
    TOKEN_INTEGER_LITERAL,
    TOKEN_FLOAT_LITERAL,
    TOKEN_OCTAL_LITERAL,
    TOKEN_HEXADECIMAL_LITERAL,
    TOKEN_BINARY_LITERAL,
    TOKEN_CHARACTER_LITERAL,
    TOKEN_STRING_LITERAL,
    TOKEN_IDENTIFIER,
    TOKEN_EOF,
    TOKEN_UNKNOWN
} TokenType;

typedef struct Token
{
    TokenType type;
    char* chars;
    size_t length;
    int line;
    int column;
} Token;

void printToken(Token* token);
void printTokenValue(Token token);
const char* tokenTypeName(TokenType type);
bool isAssignmentToken(TokenType type);
bool isTypeToken(TokenType type);
bool isComparisonToken(TokenType type);
bool isEqualityToken(TokenType type);
bool isBoolOperatorToken(TokenType type);
bool isShiftToken(TokenType type);
bool isTermToken(TokenType type);
bool isFactorToken(TokenType type);
bool isPrefixToken(TokenType type);

#endif
